algoritmo "Conversor"
var
    Angulo, S: real
inicio

     Escreva ("informe um angulo: ")
     // Solicitando um ângulo para o usuario
     
     Leia (angulo)
     // Vai ler o valor digitado e armazenar na variavel (ângulo)
     
     S <- Sen (GraupRad(angulo))
     // (S) vai ser o seno desse ângulo(número digitado) convertido de grau para radianos
     
     escreva(" O seno de ", angulo, "é igual a ", s)
     //Vai mostrar na tela uma mensagem e o resultado da conversão.


fimalgoritmo