algoritmo "Mostrando_A_Parte_inteira_Da_Raiz_Quadrada_De_Um_Número"
var

   A: Real
   // Nome da Variavel: A
   // Tipo Primitivo: Real
   
inicio

     A <- Int(RaizQ (90))// Juntando Expreções
     // qual é a parte inteira da raiz de 90?
     // A VAriavel (A) vai Receber o Resultado inteiro da raiz quadrada de 90
     // Ou seja Parte Inteira da Raiz quadrada de 90

     Escreva (A)// Escreva o valor da variavel (A) na tela
     
fimalgoritmo