algoritmo "Primeiro_Comando_De_Entrada"
var

    nome: caracter
    // Nome da variavel: nome
    // Tipo primitivo: Caracter
    
inicio

     Escreva ("Digite seu nome: ") // Vai escrever na tela ("Digite seu nome: ")
     Leia (nome) // Vai ler oque o usuario digitou e armazenar na variavel (nome)
     Escreva ("Muito prazer ",nome) // Vai escrever na tela ("Muito prazer " e o resultado da variavel nome)
     
fimalgoritmo