algoritmo "Comparar_valores_Númericos"
var

   A, B, C: Inteiro
   //Nomes das Variaveis: A, B, C
   // Tipo Primitivo: Inteiro
   
inicio

     A <- 2 // Atribuicao de valor a Variavel
     B <- 3 // Atribuicao de valor a Variavel
     C <- 5 // Atribuicao de valor a Variavel
     
     Escreva (A>2)
     //Teste lógico pra saber se (A) é Maior Que 2
     // A = 2
     // 2 Não é Maior que 2
     //Resultado: Falso
     
fimalgoritmo