algoritmo "Comparar_valores_Númericos_Operador_Lógico_Menor_Que"
var

   A, B, C: Inteiro
   //Nomes das Variaveis: A, B, C
   // Tipo Primitivo: Inteiro
   
inicio

     A <- 2 // Atribuicao de valor a Variavel
     B <- 3 // Atribuicao de valor a Variavel
     C <- 5 // Atribuicao de valor a Variavel
     
     Escreva (A<B)
     //Teste lógico pra saber se (A) é Menor que (B)
     // A = 2
     // B = 3
     // 2 é Menor Que 3
     //Resultado: Verdadeiro
     
fimalgoritmo