algoritmo "Testes_Lógicos_Com_Tabela_Verdade_1"
var

   A, B, C: Inteiro
   //Nomes das Variaveis: A, B, C
   // Tipo Primitivo: Inteiro
   
inicio

     A <- 2 // Atribuicao de valor a Variavel
     B <- 3 // Atribuicao de valor a Variavel
     C <- 5 // Atribuicao de valor a Variavel
     
     Escreva (Verdadeiro e falso)
     //Resultado: Falso
     // uma coisa verdadeira e uma falsa da em falso
     
     
     
     
fimalgoritmo