algoritmo "Mostrando_Mensagem_na_Tela"
var
   // Area de Declaracao de Variaveis
inicio

     Escreval ("Olá, Mundo!") // Escreval - Escreva e salte a linha.
     Escreva ("Me Livrei Da Maldição do Olá, Mundo!") // Escreva - Apenas escreva algo na tela.
     
     // Com esse comando (Escreva) é possivel escrever alguma coisa na tela.
     // O comando (Escreva) serve para apresentar algo na tela.

fimalgoritmo